### ISSUE TITLE
cc2652rb, baw resonator

### ISSUE THREAD

**Issue by zigastegu** [electrolama/zig-a-zig-ah#1]
Hi, it seems RB does not need XTAL, as it has Integrated Bulk Acoustic Wave (BAW) resonator.
Don't know about price difference and avalability.
Would it make a difference for pcb size?
https://www.ti.com/sitesearch/docs/universalsearch.tsp?searchTerm=cc2652rb

**Comment by omerk** [comment]
Hey @zigastegu,

Looks like samples are available but not GA just yet, price comparison from the TI Store:

![image](https://user-images.githubusercontent.com/9847/73599512-32271d80-453c-11ea-82a0-5a4d23b4bcee.png)

PCB real estate wise, doesn't make a huge difference for zzh as the form factor is dictated by the [enclosure chosen](https://twitter.com/OmerK/status/1219025454344146945). 

Pushed the draft design files in the repo, let me know if you spot anything out of the ordinary :-)
