### ISSUE TITLE
[INFORMATION] Zig-a-zig-ah USB-stick should also be compatible with turboproc's Zigbee dongle adapter for TI CC-DEVPACK-DEBUG board

### ISSUE THREAD

**Issue by Hedda** [electrolama/zig-a-zig-ah#10]
@omerk FYI, just a piece of compatibility information, the Zig-a-zig-ah USB-stick should also be compatible with the Zigbee dongle adapter for TI CC-DEVPACK-DEBUG board designed by @turboproc

- https://github.com/turboproc/Zigbee-dongle-adapter

The 6 pin connector on the Zig-a-zig-ah USB-stick should also match both the [CC1352-based Zigbee USB-dongle](https://github.com/turboproc/Zigbee-USB-dongle) by @turboproc and the [CC2652-based Zig-a-zig-ah USB-stick](https://github.com/electrolama/zig-a-zig-ah) by @omerk allowing easy connection to the TI CC-DEVPACK-DEBUG board that allow these Zigbee USB dongles to be programmed through the CJTAG interface.

- https://github.com/turboproc/Zigbee-USB-dongle
- https://github.com/electrolama/zig-a-zig-ah

**Comment by omerk** [comment]
Good to know although there is already a [debug-adapter board in the repo](https://github.com/electrolama/zig-a-zig-ah/tree/master/Debug-Adapter).
