### ISSUE TITLE
[SUGGESTION] Distribute firmware binaries for ZZH adapter via Koenkk / Z-Stack-firmware repo?

### ISSUE THREAD

**Issue by Hedda** [electrolama/zig-a-zig-ah#13]
@omerk Can I suggest you look into distributing ZZH FW binaries via Koenkk Z-Stack-firmware repo?

- https://github.com/Koenkk/Z-Stack-firmware/
  - https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator
    - https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0

The reason is that I think most people already get their CC2530 and CC2531 firmware there for open source projects like Zigbee2mqtt, ioBroker, and Home Assistant ZHA, (as well as for openHAB?), and assuming that many if not most people will be buying a Zig-a-zig-ah adapter as a direct upgrade replacement adapter for their existing CC2530/ CC2531 adapter.

That is if both yourself and @Koenkk is willing of course.

**Comment by Koenkk** [comment]
The firmwares in https://github.com/Koenkk/Z-Stack-firmware/tree/develop/coordinator/Z-Stack_3.x.0/bin actually already work on the ZZH (have them running in production).
