### ISSUE TITLE
No Signal in Z2M when using a different antenna

### ISSUE THREAD

**Issue by kennymc-c** [electrolama/zig-a-zig-ah#15]
When I connect the zzh to different antenna (dual band WiFi +9dbi), Z2M seems to have problems with reception. There are simply no signals coming in. According to dmesg, the adapter has been detected by the system. As soon as I reconnect it to the supplied antenna, the signal is coming back. Since I use the same type of antenna with a CC2530 router, I assume that the antenna itself is suitable for this. I have attached a zigbee-herdsmann debug log that might help:

https://pastebin.com/k4wAtciK

**Comment by puddly** [comment]
The zzh has a female SMA connector. Make sure your antenna is not a male RP-SMA, which will still screw on but will not actually act as an antenna:


[![Be-an-RC-God-Understanding-FPV-Connectors-SMA-vs-RP-SMA-A02](https://user-images.githubusercontent.com/32534428/85954083-822bd400-b964-11ea-94bc-7c8446a99909.jpg)](https://www.gearbest.com/blog/how-to/be-an-rc-god-understanding-fpv-connectors-sma-vs-rp-sma-811)

**Comment by kennymc-c** [comment]
Thanks, that should be the reason. My antenna is also female. I just realized now when I saw the connection. Sorry, I could have figured it out myself.
