### ISSUE TITLE
Very bad range after switching to zzh

### ISSUE THREAD

**Issue by kisseler** [electrolama/zig-a-zig-ah#17]
I tried to modernize my zigbee2mqtt hardware by replacing the CC1352P-2 dev board by this new nice great form factor zzh dongle. After some tries I made it flashing the z2m firmware and wondered why I cannot pair any devices.

I turned out, I had to approach the dongle less than one meter to pair a device. That's more than disappointing. Setiing the system back to the CC1352P-2 hardware as coordinator, I was easyly able to pair devices from next room. I tried USB extension cable and unplugging other devices to reduce interference.

Anyone else here having that problem? I wanted to make my system more and more reliable, but with zig-a-zig-ah it seems to be not the right way. Or what am I missing?

Thanks for any hint!

**Comment by omerk** [comment]
Hi @kisseler, please send me your Tindie order number to support@electrolama .com and we can go figure out what the problem is.
