### ISSUE TITLE
New ZZH unable to pair any devices

### ISSUE THREAD

**Issue by magicdude4eva** [electrolama/zig-a-zig-ah#18]
I just got the ZZH and wanted to replace my ConbeeII on a RPI4 (I flashed the current firmware via Mac)
```
./cc2538-bsl.py -p /dev/tty.usbserial-14320 -evw znp_CC26X2R1_LAUNCHXL_tirtos_ccs.hex
Opening port /dev/tty.usbserial-14320, baud 500000
Reading data from znp_CC26X2R1_LAUNCHXL_tirtos_ccs.hex
Your firmware looks like an Intel Hex file
Connecting to target...
CC1350 PG2.0 (7x7mm): 352KB Flash, 20KB SRAM, CCFG.BL_CONFIG at 0x00057FD8
Primary IEEE Address: 00:12:4B:00:21:60:01:6A
    Performing mass erase
Erasing all main bank flash sectors
    Erase done
Writing 360448 bytes starting at address 0x00000000
Write 104 bytes at 0x00057F980
    Write done
Verifying by comparing CRC32 calculations.
    Verified (match: 0x870fee48)
```

I have Zigbee2mqtt installed on latest HA (I uninstalled Zigbee2mqtt multiple times, deleted the configs and DB files, removed the stick) and I adjusted configs to either use `/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0` or just `/dev/ttyUSB0` I am not able to see our scan any new devices (yes I added `rtscts: false`, changed pan_id, ext_pan_id and network_key).

Are there any limitations with regards to channels (I am running on channel: 25)?  In removed all Zigbee devices from my ConbeeII and during the ZZH setup reset the devices multiple times without success of finding or pairing. 

Note: After uninstalling Zigbee2mqtt, deleting the database file, replacing the ZZH with the ConbeeII and rebooting HA, all the Zigbee devices are found (I literally just replace the port config pointing to the ZZH to the Conbee).

It does not look like the ZZH is dead-on-arrival, as I otherwise would be able not to flash it - or? I re-read the instructions multiple times (also tried ZHA with same results). Is there anything I missed?

**Comment by omerk** [comment]
Hi @magicdude4eva, there are no limitations on what channels can be used. Sounds like there might be an issue with the antenna.

Please drop an email with your Tindie order number to support@electrolama.com and we can figure out a solution.
