### ISSUE TITLE
Somebody tried it?

### ISSUE THREAD

**Issue by guitar9** [electrolama/zig-a-zig-ah#2]
Does somebody tried it out?
Does it work?
What are the plans for future?

**Comment by sermayoral** [comment]
@guitar9 the device is in desing stage, so it does not work yet, but it promises... :-)

**Comment by omerk** [comment]
That is correct, waiting on PCBs and parts to verify the design at the moment.

Keep an eye on [this Twitter thread](https://twitter.com/OmerK/status/1212864418155028480) for the latest info.
