### ISSUE TITLE
Flashing to use ble

### ISSUE THREAD

**Issue by MattL0** [electrolama/zig-a-zig-ah#20]
Anyone knows what is needed to use this as a ble dongle? 

I am using a sena right know. I wonder how this would perform again the sena

**Comment by MattL0** [comment]
http://www.senanetworks.com/ud100-g03.html

**Comment by omerk** [comment]
Hi @MattL0,

My interest (and experience) with these chips is mainly Zigbee related so can't really comment on Bluetooth but the product you linked seems to be a standard USB Bluetooth dongle therefore zzh is probably not what you're after. The comms between the CC2652R and your PC would be standard UART/Serial, not the usual endpoints a standard BT dongle would expose.
