### ISSUE TITLE
Suggest to ship all future zzh pre-flashed with Z-Stack coordinator firmware?

### ISSUE THREAD

**Issue by Hedda** [electrolama/zig-a-zig-ah#25]
@omerk can I suggest that @electrolama ship all future zzh sticks pre-flashed with Z-Stack coordinator application firmware?

I  believe that most of your buyers would find zzh very user-friendly if they could just plug it in and get it working straight away.

FYI, slaesh now offer pre-flashed versions of his CC2652 stick directly from his website at https://slae.sh/projects/cc2652/

![image](https://user-images.githubusercontent.com/6320001/105505527-56d65100-5cc9-11eb-8687-b05e998d1040.png)

Yes it is relatively easy for an at least semi-technical person to flash Z-Stack coordinator application firmware on CC2652R via its serial preinstalled bootloader but I guesstimate that a very large majority of your non-vocal customer-base will use it with either ZHA in Home Assistant or Zigbee2MQTT and those people would probably appreciate if the zzh stick that gets sent to them already comes pre-flashed with Z-Stack coordinator firmware so that it will work straight out-of-the-box without having to flash firmware to it first.

**Comment by omerk** [comment]
Thanks for your suggestion.
