### ISSUE TITLE
Help components eletronics 

### ISSUE THREAD

**Issue by pedroborges1** [electrolama/zig-a-zig-ah#3]
Good,  i am interested in this zigbee pen Zig-a-zig-ah.

you can send me a list of the electronic components you used ?

how do you flash this zigbee pen Zig-a-zig-ah ?

**Comment by omerk** [comment]
Hi @pedroborges1, 

This is an untested, work-in-progress design. If you're interested in the BOM, the design files are in the repo and you can open them with EAGLE.

Keep an eye on [this Twitter thread](https://twitter.com/OmerK/status/1212864418155028480) for the latest info.

**Comment by pedroborges1** [comment]
thanks you ,

I already have the  zig-a-zig-ah[1]/ Revision A[2] eagle file .

but there is another folder name debug-adapter.

I just need the zig-a-zig-ah / revision A ?

the file is not there Bom ?

 

Citando Omer Kilic <notifications@github.com>:

> Hi @pedroborges1[3],
>
> This is an untested, work-in-progress design. If you're interested  
> in the BOM, the design files are in the repo and you can open them  
> with EAGLE.
>
> Keep an eye on this Twitter thread[4] for the latest info.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub[5], or unsubscribe[6].

 

Ligações:
---------
[1] https://github.com/electrolama/zig-a-zig-ah
[2] https://github.com/electrolama/zig-a-zig-ah/tree/master/Revision%20A
[3] https://github.com/pedroborges1
[4] https://twitter.com/OmerK/status/1212864418155028480
[5]  
https://github.com/electrolama/zig-a-zig-ah/issues/3?email_source=notifications&email_token=AOQ2NEZLI2DCSCBALLOEEQLRDF3IVA5CNFSM4KS72SW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL4NJWI#issuecomment-586732761
[6]

**Comment by omerk** [comment]
As I've said, this is still a work in progress so I have not yet released anything other than the currently untested design files. If you're interested in building one at this stage you are going to have to go through what is in the repo and figure it out yourself.

**Comment by pedroborges1** [comment]
thank you ,when you are finished let me know .

 

Citando Omer Kilic <notifications@github.com>:

> As I've said, this is still a work in progress so I have not yet  
> released anything other than the currently untested design files. If  
> you're interested in building one at this stage you are going to  
> have to go through what is in the repo and figure it out yourself.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub[1], or unsubscribe[2].

 

Ligações:
---------
[1]  
https://github.com/electrolama/zig-a-zig-ah/issues/3?email_source=notifications&email_token=AOQ2NE76EO6ER2TVNGZLPY3RDG6BFA5CNFSM4KS72SW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL4UVKI#issuecomment-586762921
[2]

**Comment by pedroborges1** [comment]
good, but have you tested this zig-a-zig-ah?

how did the flash zig-a-zig -ah ?

 

Citando Omer Kilic <notifications@github.com>:

> As I've said, this is still a work in progress so I have not yet  
> released anything other than the currently untested design files. If  
> you're interested in building one at this stage you are going to  
> have to go through what is in the repo and figure it out yourself.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub[1], or unsubscribe[2].

 

Ligações:
---------
[1]  
https://github.com/electrolama/zig-a-zig-ah/issues/3?email_source=notifications&email_token=AOQ2NE76EO6ER2TVNGZLPY3RDG6BFA5CNFSM4KS72SW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL4UVKI#issuecomment-586762921
[2]

**Comment by pedroborges1** [comment]
good, i used an ikea repeater for the zigbee network, but even so a  
sensor sometimes stops working.

I think the signal doesn’t reach that sensor well, which is the one  
that’s farthest away.

some solution to improve this ?
 

Citando pedro <pedrofilipe32@sapo.pt>:

> thank you ,when you are finished let me know .
>
>  
>
> Citando Omer Kilic <notifications@github.com>:
>
>> As I've said, this is still a work in progress so I have not yet  
>> released anything other than the currently untested design files.  
>> If you're interested in building one at this stage you are going to  
>> have to go through what is in the repo and figure it out yourself.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub[1], or unsubscribe[2].
>
>  

 

Ligações:
---------
[1]  
https://github.com/electrolama/zig-a-zig-ah/issues/3?email_source=notifications&email_token=AOQ2NE76EO6ER2TVNGZLPY3RDG6BFA5CNFSM4KS72SW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEL4UVKI#issuecomment-586762921
[2]
