### ISSUE TITLE
[SUGGESTION] Market and sell an initial of batch Zig-a-zig-ah! adapters via the Crowd Supply site?

### ISSUE THREAD

**Issue by Hedda** [electrolama/zig-a-zig-ah#6]
@omerk I like to suggest that you market and sell an initial small batch of your Zig-a-zig-ah! USB-adapters via the **Crowd Supply** crowdsourcing site for electronics hardware at [crowdsupply.com](https://www.crowdsupply.com)

- https://www.crowdsupply.com

@omerk I understand that you already have existing plans to sell hardware via Tindie. Crowd Supply is similar but different than Tindie in that Crowd Supply is not just a marketplace but specifically, a crowdsourcing platform which has staff that will actively help you with advice on running a crowdsourcing campaign for funding, manufacturing, and marketing. 

Most importantly, Crowd Supply has a great international community so I think that also launching a crowdsourcing campaign on Crowd Supply would help you grow a much larger community around Electrolama and the Zig-a-zig-ah project. Many electronics products have initially first launched on Crowd Supply then only after proven successful and gaining experience of running a small crowdsourcing campaign with a smaller batch next launch larger crowdsourcing campaigns with a more finished version of the same or similar products on Kickstarter and/or Indiegogo.

- https://www.crowdsupply.com/about

I have no personal affiliations with **Crowd Supply** or its owers/staff, but I backed a couple of projects there myself and know that their site is meant exactly for helping crowdsource funds and initial launch of a small batch of this type of early version hobby-class hardware kits meant for developers and advanced users who are willing to accept bleeding-edge hardware which might not yet be a finished product. 

Personally I can recommend that you compare this μArt hardware by Karoly Pados which I backed:

- https://www.crowdsupply.com/pylo/muart

I think that his launch for a small initial batch of μArt (pronounced "Muart") on Crowd Supply was a perfect example of how a crowdsourcing campaign for this type of niche electronics hardware should be handled before its a mature product.

**Comment by omerk** [comment]
Hey @Hedda, thanks for reaching out.

I am familiar with Crowdsupply and looking at distribution/logistics is on my list of things to do for the weekend, after I do some further testing with the prototypes so that I can issue files for manufacturing a small batch.

Getting the design verified is my current priority, rest will follow soon after 😄 

Cheers!

**Comment by Hedda** [comment]
@omerk Cool! Regardless if you go with that or not I still highly recommend that you read through μArt updates by Karoly Pados as a great example on how to run and update the community during such a campaign, so do checkout update history here https://www.crowdsupply.com/pylo/muart/updates
