### ISSUE TITLE
[NEW PROJECT SUGGESTION] Zigbee 3.0 and Z-Wave 700 platform series combo USB-stick

### ISSUE THREAD

**Issue by Hedda** [electrolama/zig-a-zig-ah#7]
Hi Omar! I follow you on Electrolama, hope it is OK to submit this as a suggestion for a new project.

Suggest you consider making a "combo" USB-stick supporting both Zigbee 3.0 & Z-Wave 700 series.

I believe that should be a good market for a "combo" USB-stick if Zigbee 3.0 coordinator & Z-Wave 700 (Gen7) platform series controller could be offered as a combination on the same USB-stick and it was less expensive to buy then to buy a separate USB-sticks for each protocol. As you probably know both Zigbee 3.0 and the Z-Wave 700 platform series are backwards compatible with previous versions of those protocols, so a such combo USB-stick could probably be marketed as the most compatible USB-stick for DIY home automation controllers in the world.

Not sure if you knew but there is a very popular combo USB-stick already available, it however only supports Zigbee HA 1.2 and Z-Wave 500 (Gen5) series; Nortek GoControl QuickStick Combo Model HUSBZB-1 (Zigbee & Z-Wave USB Adapter) is supported natively by Home Assistant's built-in ZHA and Z-Wave integrations. As I understand it, that HUSBZB-1 is based on two separate Silicon Labs chips for Zigbee and Z-Wave, and it presents itself to the operating system as two separate serial adapters. "The Model HUSBZB-1 is a USB stick that houses both a Z-Wave and Zigbee radio. Designed for OEMs that want to provide dual functionality when being used with a host device.":

https://www.nortekcontrol.com/products/2gig/husbzb-1-gocontrol-quickstick-combo/

Silicon Labs released a UZB-7 / UZB7 based on EFR32ZG14 as a reference design for making Z-Wave 700 platform series USB-stick controllers.

https://www.silabs.com/documents/public/data-sheets/DSH14483.pdf

Silicon Labs also has Zigbee chips like EFR32MG13 (example: EFR32MG13P732F512GM32-C) and others design to be used in a Zigbee coordinator.

https://www.silabs.com/wireless/zigbee

As I understand it, both those chips belong to the "Gecko" series by Silicon Labs.

Anyway, chips from Silicon Labs would be the obvious choice for a combo USB-stick since they own the Z-Wave specification and are also according to them the leading provider of Zigbee solutions as as as for Bluetooth solutions.

https://www.silabs.com/products/wireless/mesh-networking/z-wave/700-platform

PS: I don't have the skills to contribute to a hardware design but I would definitely buy one or back such a combo USB-stick if was launched as a campaign on a popular global crowdfunding platform.

**Comment by omerk** [comment]
Thanks for the links and background info @Hedda

I must admit I am a lot more familiar with Zigbee than Z-Wave so that is what I am focusing on with this design but once zzh gets a bit more mature and I am looking for my next weekend project, I will certainly revisit this discussion!
